const test = require('node:test');
const assert = require('node:assert/strict');
const { createServer } = require('../../src/server');
const { createArtifact } = require('../../src/core/artifact');
const { RunStore } = require('../../src/core/store');
const { RUNTIME_CONTRACT_CUTOFF_MS } = require('../../src/core/presentation');

async function request(base, path, options = {}) {
  const response = await fetch(`${base}${path}`, { ...options, headers: { 'content-type': 'application/json', ...(options.headers || {}) } });
  const text = await response.text();
  let body; try { body = JSON.parse(text); } catch { body = text; }
  return { response, body };
}

test('server supports spin, concept, artifact, creation, and opaque run routes', async (t) => {
  const server = createServer({ fixtureMode: true });
  await new Promise((resolve) => server.listen(0, resolve));
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}`;
  const spin = await request(base, '/api/spin', { method: 'POST', body: JSON.stringify({ seed: 'integration', requestId: 'integration-spin' }) });
  assert.equal(spin.response.status, 200);
  const run = spin.body;
  const apiIds = run.selectedApis.map((api) => api.id);
  const concept = await request(base, `/api/runs/${run.runId}/concept`, { method: 'POST', body: JSON.stringify({ requestId: 'integration-concept', appName: 'Weather Dealer', premise: 'A weather auction where unrelated public signals become one theatrical market.', playerAction: 'Press the dealer button to settle the next absurd auction.', noveltyDelta: 'The selected signals decide the auction rules.', apiIds, apiRoles: run.selectedApis.map((api) => ({ apiId: api.id, essentialRole: `${api.name} supplies the dealer\'s next essential signal.`, operations: api.operations.map((operation) => operation.id) })), causalChain: run.selectedApis.map((api, index) => ({ order: index + 1, apiId: api.id, action: `turn ${api.name} into the next auction rule` })), dependency: { fromApiId: apiIds[0], to: 'rules', toApiId: apiIds[1], explanation: 'The first signal determines how the next one is interpreted.' }, interaction: { controls: ['settle auction'], outcome: 'The dealer reveals a changing result.' }, visualDirection: { style: 'maximalist auction theatre', palette: 'saffron, ink, and cyan', typography: 'oversized editorial serif', motion: 'cards sweep like auction paddles' }, bannedShapeAssessment: { plainDashboard: false, plainSearch: false, plainQuiz: false, randomFactDisplay: false, thinClone: false, plausibleStartupPitch: false, explanation: 'This is a staged collision, not a startup pitch.' } }) });
  assert.equal(concept.response.status, 200);
  const selected = run.selectedApis.map((api) => ({ apiId: api.id, operationId: api.operations[0].id }));
  const html = createArtifact({ appName: 'Weather Dealer', selected });
  const artifact = await request(base, `/api/runs/${run.runId}/artifact`, { method: 'POST', body: JSON.stringify({ requestId: 'integration-artifact', html }) });
  assert.equal(artifact.response.status, 200);
  const page = await fetch(`${base}/c/${artifact.body.creationId}`);
  assert.equal(page.status, 200);
  assert.match(page.headers.get('content-security-policy'), /frame-src 'self'/);
  const ownerHtml = await page.text();
  assert.match(ownerHtml, /sandbox="allow-scripts"/);
  assert.match(ownerHtml, /Randomware showcase/);
  assert.match(ownerHtml, /See other specimens/);
  assert.match(ownerHtml, /Spin your own/);
  assert.match(ownerHtml, /— get /);
  assert.match(ownerHtml, /docs|github|api/i);
  assert.match(ownerHtml, /<link rel="stylesheet" href="\/creation\.css">/);
  assert.doesNotMatch(ownerHtml, /<style[\s>]/);
  assert.doesNotMatch(ownerHtml, /<script[\s>]/);
  const creationCss = await fetch(`${base}/creation.css`);
  assert.equal(creationCss.status, 200);
  const creationCssText = await creationCss.text();
  assert.match(creationCssText, /\.rw-frame/);
  assert.match(creationCssText, /min-height:390px/);
  assert.match(creationCssText, /height:min\(88vh,1000px\)/);
  const ownerCsp = page.headers.get('content-security-policy');
  assert.match(ownerCsp, /frame-ancestors https:\/\/chatgpt\.com/);
  assert.match(ownerCsp, /https:\/\/web-sandbox\.oaiusercontent\.com/);
  assert.match(ownerCsp, /https:\/\/\*\.web-sandbox\.oaiusercontent\.com/);
  const download = await fetch(`${base}/api/creations/${artifact.body.creationId}/download`);
  assert.match(download.headers.get('content-disposition'), /attachment/);
  assert.match(await download.text(), /window\.randomware/);
  const spec = await fetch(`${base}/api/creations/${artifact.body.creationId}/spec`);
  assert.equal(spec.status, 200);
  assert.match(await spec.text(), /Weather Dealer/);
  const specDownload = await fetch(`${base}/api/creations/${artifact.body.creationId}/spec/download`);
  assert.match(specDownload.headers.get('content-disposition'), /attachment/);
  assert.match(await specDownload.text(), /causal chain/i);
  const generated = await fetch(`${base}/run/${artifact.body.creationId}`);
  assert.equal(generated.status, 200);
  const runtimeCsp = generated.headers.get('content-security-policy');
  assert.match(runtimeCsp, /https:\/\/web-sandbox\.oaiusercontent\.com/);
  assert.match(runtimeCsp, /https:\/\/\*\.web-sandbox\.oaiusercontent\.com/);
  assert.match(await generated.text(), /window\.randomware/);
  const recent = await request(base, '/api/creations/recent');
  assert.ok(recent.body.some((creation) => creation.creationId === artifact.body.creationId));
  const index = await fetch(`${base}/`);
  const indexHtml = await index.text();
  assert.match(indexHtml, /For judges/);
  assert.match(indexHtml, /Weather Dealer/);
  assert.doesNotMatch(indexHtml, /Loading/);
  const requestsPage = await fetch(`${base}/api/creations/${artifact.body.creationId}/requests`);
  assert.match(await requestsPage.text(), /Request receipts/);
  const requestsRaw = await fetch(`${base}/api/creations/${artifact.body.creationId}/requests?format=raw`);
  assert.deepEqual(await requestsRaw.json(), []);
  const dataflowPage = await fetch(`${base}/api/creations/${artifact.body.creationId}/dataflow`);
  assert.match(await dataflowPage.text(), /Dataflow, in order/);
  const reportConfirm = await fetch(`${base}/api/creations/${artifact.body.creationId}/report`);
  assert.match(await reportConfirm.text(), /Report and hide/);
  const report = await fetch(`${base}/api/creations/${artifact.body.creationId}/report`, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: 'reason=test' });
  assert.match(await report.text(), /Report received/);
  const hidden = await request(base, '/api/creations/recent');
  assert.ok(!hidden.body.some((creation) => creation.creationId === artifact.body.creationId));
  const forbidden = await request(base, `/api/creations/${artifact.body.creationId}/unpublish`, { method: 'POST', body: '{}' });
  assert.equal(forbidden.response.status, 403);
  const unpublished = await request(base, `/api/creations/${artifact.body.creationId}/unpublish`, { method: 'POST', headers: { authorization: 'Bearer local-owner-token' }, body: '{}' });
  assert.equal(unpublished.body.status, 'unpublished');
  const removed = await fetch(`${base}/c/${artifact.body.creationId}`);
  assert.match(await removed.text(), /Creation removed/);
});

test('server refuses to execute a preserved pre-runtime-contract artifact', async (t) => {
  const store = new RunStore();
  const run = store.createRun({ requestId: 'server-early-runtime', selectedApis: [{ apiId: 'open-meteo', operationIds: ['forecast'] }] });
  store.acceptConcept(run.id, { requestId: 'server-early-concept', appName: 'Early Weather Clerk', apiIds: ['open-meteo'] });
  store.acceptArtifact(run.id, { requestId: 'server-early-artifact', html: '<script>window.earlyArtifactExecuted=true</script>', bytes: 50 });
  run.revisions[0].at = RUNTIME_CONTRACT_CUTOFF_MS - 1;
  const server = createServer({ fixtureMode: true, store });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  t.after(() => server.close());

  const response = await fetch(`http://127.0.0.1:${server.address().port}/run/${run.creationId}`);
  const html = await response.text();
  assert.equal(response.status, 200);
  assert.match(html, /Runtime retired/);
  assert.match(html, /pre-contract specimen is not executed/);
  assert.doesNotMatch(html, /window\.randomware|earlyArtifactExecuted/);
  assert.equal(run.lastCapabilityExpiresAt, undefined);
});

test('MCP surface exposes eight annotated tools', async (t) => {
  const server = createServer({ fixtureMode: true });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}`;
  const initialize = await request(base, '/mcp', { method: 'POST', body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'integration', version: '1' } } }) });
  assert.equal(initialize.response.status, 200);
  assert.equal(initialize.body.result.protocolVersion, '2025-06-18');
  const ready = await request(base, '/mcp', { method: 'POST', body: JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }) });
  assert.equal(ready.response.status, 202);
  const resources = await request(base, '/mcp', { method: 'POST', body: JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'resources/list' }) });
  assert.equal(resources.body.result.resources[0].uri, 'ui://widget/randomware.html');
  const template = await request(base, '/mcp', { method: 'POST', body: JSON.stringify({ jsonrpc: '2.0', id: 3, method: 'resources/read', params: { uri: 'ui://widget/randomware.html' } }) });
  assert.equal(template.body.result.contents[0].mimeType, 'text/html;profile=mcp-app');
  const result = await request(base, '/mcp', { method: 'POST', body: JSON.stringify({ jsonrpc: '2.0', id: 4, method: 'tools/list' }) });
  assert.equal(result.response.status, 200);
  assert.equal(result.body.result.tools.length, 8);
  assert.ok(result.body.result.tools.every((tool) => tool.description.startsWith('Use this')));
  assert.ok(result.body.result.tools.every((tool) => tool.annotations && typeof tool.annotations.readOnlyHint === 'boolean'));
  const annotations = Object.fromEntries(result.body.result.tools.map((tool) => [tool.name, tool.annotations]));
  for (const name of ['open_randomware', 'spin_apis', 'get_run', 'mutate_creation', 'record_choreography_failure']) assert.equal(annotations[name].openWorldHint, false);
  for (const name of ['submit_concept', 'submit_artifact', 'submit_repair']) assert.equal(annotations[name].openWorldHint, true);
  const open = result.body.result.tools.find((tool) => tool.name === 'open_randomware');
  assert.equal(open._meta.ui.resourceUri, 'ui://widget/randomware.html');
  const openCall = await request(base, '/mcp', { method: 'POST', body: JSON.stringify({ jsonrpc: '2.0', id: 5, method: 'tools/call', params: { name: 'open_randomware', arguments: {} } }) });
  assert.deepEqual(openCall.body.result.content, [{ type: 'text', text: 'Randomware slot mounted.' }]);
  assert.equal(openCall.body.result.structuredContent.ok, true);
  const get = await fetch(`${base}/mcp`);
  assert.equal(get.status, 405);
});

test('failed artifact keeps a nonblank owner-controlled death certificate', async (t) => {
  const server = createServer({ fixtureMode: true });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}`;
  const spin = await request(base, '/api/spin', { method: 'POST', body: JSON.stringify({ seed: 'failure', requestId: 'failure-spin' }) });
  const apiIds = spin.body.selectedApis.map((entry) => entry.id);
  const concept = await request(base, `/api/runs/${spin.body.runId}/concept`, { method: 'POST', body: JSON.stringify({ requestId: 'failure-concept', appName: 'Failure Sample', premise: 'A failure sample where selected sources stage one careful collapse.', playerAction: 'Press the collapse button to observe the safe failure.', noveltyDelta: 'The collapse itself is the specimen.', apiIds, apiRoles: spin.body.selectedApis.map((entry) => ({ apiId: entry.id, essentialRole: `${entry.name} supplies an essential collapse signal.`, operations: entry.operations.map((operation) => operation.id) })), causalChain: spin.body.selectedApis.map((entry, index) => ({ order: index + 1, apiId: entry.id, action: `turn ${entry.name} into a collapse signal` })), dependency: { fromApiId: apiIds[0], to: 'rules', toApiId: apiIds[1], explanation: 'The first signal changes the collapse rule.' }, interaction: { controls: ['collapse'], outcome: 'The collapse stops with a readable cause.' }, visualDirection: { style: 'maximalist failure theatre', palette: 'black and coral', typography: 'oversized serif', motion: 'a red line snaps shut' }, bannedShapeAssessment: { plainDashboard: false, plainSearch: false, plainQuiz: false, randomFactDisplay: false, thinClone: false, plausibleStartupPitch: false, explanation: 'The failure is the deliberately theatrical output.' } }) });
  assert.equal(concept.response.status, 200);
  const failed = await request(base, `/api/runs/${spin.body.runId}/artifact`, { method: 'POST', body: JSON.stringify({ requestId: 'failure-artifact', html: '<!doctype html><html><head></head><body>unsafe</body></html>' }) });
  assert.equal(failed.response.status, 422);
  const run = await request(base, `/api/runs/${spin.body.runId}`);
  const page = await fetch(`${base}/c/${run.body.creationId}`);
  assert.equal(page.status, 200);
  assert.match(await page.text(), /Failed Creation/);
});

test('failed artifact revisions retain inspectable source and fingerprints', async (t) => {
  const server = createServer({ fixtureMode: true });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}`;
  const spin = await request(base, '/api/spin', { method: 'POST', body: JSON.stringify({ seed: 'inspect-revisions', requestId: 'inspect-revisions-spin' }) });
  const ids = spin.body.selectedApis.map((entry) => entry.id);
  const concept = await request(base, `/api/runs/${spin.body.runId}/concept`, { method: 'POST', body: JSON.stringify({ requestId: 'inspect-revisions-concept', appName: 'Inspectable Failure', premise: 'A deliberately inspectable failed collision specimen for review.', playerAction: 'Press the review button to inspect each failed source revision.', noveltyDelta: 'The failure remains a readable artifact, not a blank page.', apiIds: ids, apiRoles: spin.body.selectedApis.map((entry) => ({ apiId: entry.id, essentialRole: `${entry.name} supplies an inspectable failure signal.`, operations: entry.operations.map((operation) => operation.id) })), causalChain: spin.body.selectedApis.map((entry, index) => ({ order: index + 1, apiId: entry.id, action: `turn ${entry.name} into an inspectable failure rule` })), dependency: { fromApiId: ids[0], to: 'rules', toApiId: ids[1], explanation: 'The first source changes the next failure rule.' }, interaction: { controls: ['review'], outcome: 'The reviewer sees a changing failed revision.' }, visualDirection: { style: 'maximalist review theatre', palette: 'black and cyan', typography: 'oversized serif', motion: 'revision cards turn over' }, bannedShapeAssessment: { plainDashboard: false, plainSearch: false, plainQuiz: false, randomFactDisplay: false, thinClone: false, plausibleStartupPitch: false, explanation: 'This is a failure review, not a product dashboard.' } }) });
  assert.equal(concept.response.status, 200);
  const first = '<!doctype html><html><head></head><body>first failed source</body></html>';
  const firstFailure = await request(base, `/api/runs/${spin.body.runId}/artifact`, { method: 'POST', body: JSON.stringify({ requestId: 'inspect-revisions-artifact', html: first }) });
  assert.equal(firstFailure.response.status, 422);
  const second = '<!doctype html><html><head></head><body>second failed source</body></html>';
  const secondFailure = await request(base, `/api/runs/${spin.body.runId}/repair`, { method: 'POST', body: JSON.stringify({ requestId: 'inspect-revisions-repair', html: second }) });
  assert.equal(secondFailure.response.status, 422);
  const rev1 = await fetch(`${base}/api/creations/${firstFailure.body.creationId}/source?revision=1`);
  const rev2 = await fetch(`${base}/api/creations/${firstFailure.body.creationId}/source?revision=2`);
  assert.match(await rev1.text(), /first failed source/);
  assert.match(await rev2.text(), /second failed source/);
  assert.equal(secondFailure.body.revisions[0].bytes, Buffer.byteLength(first));
  assert.equal(secondFailure.body.revisions[1].bytes, Buffer.byteLength(second));
  assert.match(secondFailure.body.revisions[0].sha256, /^[a-f0-9]{64}$/);
  assert.match(secondFailure.body.revisions[1].sha256, /^[a-f0-9]{64}$/);
});
