const crypto = require('node:crypto');
const { phases } = require('./store');

const makeId = (prefix) => `${prefix}_${crypto.randomBytes(16).toString('hex')}`;
const parse = (value, fallback) => { try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } };

class D1RunStore {
  constructor(db) { if (!db) throw new Error('d1_binding_required'); this.db = db; }

  async hydrate(row) {
    if (!row) throw new Error('run_not_found');
    const metadata = parse(row.metadata_json, {});
    const revisionRows = await this.db.prepare('SELECT revision, request_id, html, bytes, sha256, status, created_at FROM artifact_revisions WHERE run_id = ? ORDER BY revision').bind(row.id).all();
    const requestRows = await this.db.prepare('SELECT api_id, operation_id, status, bytes, cache_hit, started_at, ended_at FROM runtime_requests WHERE run_id = ? ORDER BY id').bind(row.id).all();
    return { id: row.id, requestId: row.request_id, phase: row.phase, selectedApis: parse(row.selected_apis_json, []), history: parse(row.history_json, []), concept: parse(row.concept_json, null), conceptHistory: metadata.conceptHistory || [], revisions: (revisionRows.results || []).map((item) => ({ revision: item.revision, requestId: item.request_id, html: item.html, bytes: item.bytes, sha256: item.sha256, status: item.status, at: item.created_at })), repairCount: row.repair_count || 0, failure: row.failure_code ? { code: row.failure_code } : null, events: metadata.events || [], createdAt: row.created_at, creationId: row.creation_id, runtimeRequests: (requestRows.results || []).map((item) => ({ apiId: item.api_id, operationId: item.operation_id, status: item.status, bytes: item.bytes, cacheHit: Boolean(item.cache_hit), startedAt: item.started_at, endedAt: item.ended_at })), listed: metadata.listed !== false, reported: Boolean(metadata.reported), unpublished: Boolean(metadata.unpublished), lastCapabilityExpiresAt: metadata.lastCapabilityExpiresAt || null };
  }

  async getRun(runId) { const row = await this.db.prepare('SELECT * FROM runs WHERE id = ?').bind(runId).first(); return this.hydrate(row); }

  async save(run) {
    await this.db.prepare('UPDATE runs SET phase = ?, selected_apis_json = ?, history_json = ?, concept_json = ?, creation_id = ?, failure_code = ?, repair_count = ?, metadata_json = ? WHERE id = ?').bind(run.phase, JSON.stringify(run.selectedApis), JSON.stringify(run.history || []), run.concept ? JSON.stringify(run.concept) : null, run.creationId, run.failure?.code || null, run.repairCount || 0, JSON.stringify({ conceptHistory: run.conceptHistory || [], events: run.events || [], listed: run.listed !== false, reported: Boolean(run.reported), unpublished: Boolean(run.unpublished), lastCapabilityExpiresAt: run.lastCapabilityExpiresAt || null }), run.id).run();
    return run;
  }

  async createRun({ requestId, selectedApis, history = [] }) {
    const existing = await this.db.prepare('SELECT * FROM runs WHERE request_id = ?').bind(requestId).first(); if (existing) return this.hydrate(existing);
    const run = { id: makeId('run'), requestId, phase: phases.SPINNED, selectedApis: structuredClone(selectedApis), history: structuredClone(history), concept: null, conceptHistory: [], revisions: [], repairCount: 0, failure: null, events: [{ type: 'spin_received', at: Date.now() }], createdAt: Date.now(), creationId: null, runtimeRequests: [], listed: true, reported: false, unpublished: false };
    await this.db.prepare('INSERT INTO runs (id, request_id, phase, selected_apis_json, history_json, created_at, repair_count, metadata_json) VALUES (?, ?, ?, ?, ?, ?, 0, ?)').bind(run.id, requestId, run.phase, JSON.stringify(run.selectedApis), JSON.stringify(run.history), run.createdAt, JSON.stringify({ events: run.events, listed: true })).run();
    return run;
  }

  async findByCreation(creationId) { const row = await this.db.prepare('SELECT * FROM runs WHERE creation_id = ?').bind(creationId).first(); return this.hydrate(row); }
  async listCreations() { const rows = await this.db.prepare('SELECT * FROM runs WHERE creation_id IS NOT NULL ORDER BY created_at DESC LIMIT 2000').all(); return Promise.all((rows.results || []).map((row) => this.hydrate(row))); }
  async unhealthyIds() { const rows = await this.db.prepare("SELECT api_id FROM api_health WHERE status != 'healthy'").all(); return new Set((rows.results || []).map((row) => row.api_id)); }

  async acceptConcept(runId, concept) { const run = await this.getRun(runId); if (run.concept && run.concept.requestId === concept.requestId) return run; if (run.phase !== phases.SPINNED || run.concept) throw new Error('phase_or_idempotency'); const selectedIds = run.selectedApis.map((api) => api.apiId).sort(); if (JSON.stringify(selectedIds) !== JSON.stringify([...concept.apiIds].sort())) throw new Error('immutable_api_set'); run.concept = structuredClone(concept); run.phase = phases.CONCEPT_ACCEPTED; run.events.push({ type: 'concept_accepted', at: Date.now() }); return this.save(run); }
  async rerollConcept(runId, { requestId, appName = '', premise = '' } = {}) { const run = await this.getRun(runId); if (run.phase !== phases.SPINNED || run.concept) throw new Error('phase_or_idempotency'); run.conceptHistory.push({ requestId, appName: String(appName).slice(0, 48), premise: String(premise).slice(0, 180), at: Date.now() }); run.events.push({ type: 'concept_rerolled', at: Date.now() }); return this.save(run); }

  async acceptArtifact(runId, { requestId, html, sha256, bytes }) { const run = await this.getRun(runId); if (run.revisions.some((revision) => revision.requestId === requestId)) return run; if (![phases.CONCEPT_ACCEPTED, phases.BUILDING].includes(run.phase)) throw new Error('phase_or_idempotency'); run.phase = phases.COMPLETED; run.creationId = run.creationId || makeId('creation'); const revision = { revision: 1, requestId, html, sha256, bytes, status: 'accepted', at: Date.now() }; run.revisions.push(revision); run.events.push({ type: 'artifact_received', at: Date.now() }, { type: 'deployed', at: Date.now() }); await this.db.prepare('INSERT INTO artifact_revisions (run_id, revision, request_id, html, bytes, sha256, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(run.id, 1, requestId, html, bytes, sha256, 'accepted', revision.at).run(); return this.save(run); }
  async recordArtifactFailure(runId, { requestId, code, html }) { const run = await this.getRun(runId); if (![phases.CONCEPT_ACCEPTED, phases.BUILDING].includes(run.phase)) throw new Error('phase_or_idempotency'); run.phase = phases.REPAIR_REQUESTED; run.creationId = run.creationId || makeId('creation'); run.failure = { code, requestId, html }; const revision = { revision: 1, requestId, html, status: 'failed', at: Date.now() }; run.revisions.push(revision); run.events.push({ type: 'artifact_received', at: Date.now() }, { type: 'repair_requested', at: Date.now() }); await this.db.prepare('INSERT INTO artifact_revisions (run_id, revision, request_id, html, bytes, sha256, status, created_at) VALUES (?, ?, ?, ?, 0, NULL, ?, ?)').bind(run.id, 1, requestId, html, 'failed', revision.at).run(); return this.save(run); }
  async acceptRepair(runId, { requestId, html, sha256, bytes }) { const run = await this.getRun(runId); if (run.revisions.some((revision) => revision.requestId === requestId)) return run; if (run.phase !== phases.REPAIR_REQUESTED || run.repairCount >= 1) throw new Error('repair_limit'); run.repairCount += 1; run.phase = phases.COMPLETED; run.creationId = run.creationId || makeId('creation'); const revision = { revision: 2, requestId, html, sha256, bytes, status: 'accepted', at: Date.now() }; run.revisions.push(revision); run.events.push({ type: 'repair_artifact_received', at: Date.now() }, { type: 'deployed', at: Date.now() }); await this.db.prepare('INSERT INTO artifact_revisions (run_id, revision, request_id, html, bytes, sha256, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(run.id, 2, requestId, html, bytes, sha256, 'accepted', revision.at).run(); return this.save(run); }
  async recordRepairFailure(runId, { requestId, code, html }) { const run = await this.getRun(runId); if (run.phase !== phases.REPAIR_REQUESTED || run.repairCount >= 1) throw new Error('repair_limit'); run.repairCount += 1; run.phase = phases.FAILED; run.creationId = run.creationId || makeId('creation'); run.failure = { code: code || 'repair_failed', requestId, html }; const revision = { revision: 2, requestId, html, status: 'failed', at: Date.now() }; run.revisions.push(revision); run.events.push({ type: 'repair_artifact_received', at: Date.now() }, { type: 'failed', code: 'repair_failed', at: Date.now() }); await this.db.prepare('INSERT INTO artifact_revisions (run_id, revision, request_id, html, bytes, sha256, status, created_at) VALUES (?, ?, ?, ?, 0, NULL, ?, ?)').bind(run.id, 2, requestId, html, 'failed', revision.at).run(); return this.save(run); }

  async fail(runId, code, detail = '') { const run = await this.getRun(runId); run.phase = phases.FAILED; run.failure = { code, detail }; run.events.push({ type: 'failed', code, at: Date.now() }); return this.save(run); }
  async assertRuntimeQuota(runId, quotas = {}) { const count = await this.db.prepare("SELECT COUNT(*) AS count, COALESCE(SUM(bytes), 0) AS bytes FROM runtime_requests WHERE run_id = ? AND status = 'ok'").bind(runId).first(); if (count.count >= (quotas.jsonCalls || 30) || count.bytes >= (quotas.adaptedBytes || 1024 * 1024)) throw new Error('capacity_reached'); return { completed: count.count, bytes: count.bytes }; }
  async logRuntime(runId, request) { const startedAt = request.startedAt || Date.now(); const endedAt = Date.now(); await this.db.prepare('INSERT INTO runtime_requests (run_id, api_id, operation_id, status, bytes, cache_hit, started_at, ended_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(runId, request.apiId, request.operationId, request.status, request.bytes || 0, request.cacheHit ? 1 : 0, startedAt, endedAt).run(); return { ...request, runId, startedAt, endedAt }; }
  async dataflow(runId) { const run = await this.getRun(runId); const calls = new Set(run.runtimeRequests.filter((row) => row.status === 'ok').map((row) => row.apiId)); const expired = run.lastCapabilityExpiresAt && Date.now() >= run.lastCapabilityExpiresAt; return run.selectedApis.map((entry, index) => ({ apiId: entry.apiId, operationIds: entry.operationIds, status: calls.has(entry.apiId) ? 'observed' : (expired ? 'unused' : (run.phase === phases.COMPLETED ? 'not_yet_observed' : 'pending')), order: index + 1 })); }
  async reportCreation(creationId, reason = 'unspecified') { const run = await this.findByCreation(creationId); run.reported = true; run.listed = false; run.events.push({ type: 'reported', reason: String(reason).slice(0, 120), at: Date.now() }); return this.save(run); }
  async unpublishCreation(creationId) { const run = await this.findByCreation(creationId); run.unpublished = true; run.listed = false; run.events.push({ type: 'unpublished', at: Date.now() }); return this.save(run); }
}

module.exports = { D1RunStore };
